=== nordic-institute/X-Road/src/signer/src/main/resources/keyconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://x-road.eu/xsd/xroad.xsd"
    xmlns:jxb="https://jakarta.ee/xml/ns/jaxb" jxb:version="3.0"
    targetNamespace="http://x-road.eu/xsd/xroad.xsd" xmlns:id="http://x-road.eu/xsd/identifiers">

    <import namespace="http://x-road.eu/xsd/identifiers" schemaLocation="../../../../common/common-util/src/main/resources/identifiers.xsd"/>
    <element name="keyConf" type="tns:KeyConfType"/>

    <complexType name="KeyConfType">
        <sequence>
            <element name="device" maxOccurs="unbounded" minOccurs="0" type="tns:DeviceType"/>
        </sequence>
    </complexType>

    <complexType name="KeyType">
        <annotation>
            <documentation>
                Encapsulates pointer to a key in keystore.
                Interpretation of the contents of the string depend on
                the type of the key.
            </documentation>
        </annotation>
        <sequence>
            <element name="friendlyName" type="string">
                <annotation>
                    <documentation>Name that is displayed in UI.</documentation>
                </annotation>
            </element>
            <element name="label" type="string" minOccurs="0">
                <annotation>
                    <documentation>Label of the key.</documentation>
                </annotation>
            </element>
            <element name="keyId" type="string" minOccurs="0">
                <annotation>
                    <documentation>Unique identifier for the key.
Keys are identified with hash of the public key.</documentation>
                </annotation>
            </element>
            <element minOccurs="0" name="publicKey" type="base64Binary">
                <annotation>
                    <documentation>Public key corresponding to the private key.</documentation>
                </annotation>
            </element>
            <element minOccurs="0" name="certRequest" type="tns:CertRequestType"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>Outstanding certificate request for this key.</documentation>
                </annotation>
            </element>
            <element name="cert" type="tns:CertificateType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>Certificate(s) associated with the key.</documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="ocspRequestKey">
                <annotation>
                    <documentation>This is PKCS#12 file that contains key and certificate for signing OCSP requests.
The content of the element is base64-encoded PKCS#12 file.</documentation>
                </annotation>
                <complexType>
                    <simpleContent>
                        <extension base="base64Binary">
                            <attribute name="cert" type="IDREF" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>
        </sequence>
        <attribute name="usage" type="tns:KeyUsage"/>
    </complexType>
    <simpleType name="KeyUsage">
        <annotation>
            <documentation>What is the purpose of this key. Possible options: authentication for security server or signing on behalf of particular member.</documentation>
            <appinfo>
                <jxb:javaType name="ee.ria.xroad.signer.protocol.dto.KeyUsageInfo" parseMethod="valueOf" printMethod="name"/>
             </appinfo>
        </annotation>
        <restriction base="string">
            <enumeration value="SIGNING"/>
            <enumeration value="AUTHENTICATION"/>
        </restriction>
    </simpleType>
    <complexType name="CertificateType">
        <sequence>
            <element minOccurs="0" name="memberId" type="id:XRoadClientIdentifierType">
                <annotation>
                    <documentation>If this certificate belongs to signing key, then this element contains identifier of the member that uses this certificate.</documentation>
                </annotation>
            </element>
            <element name="contents" type="base64Binary"/>
            <element name="status" type="string" minOccurs="0">
                <annotation>
                    <documentation>Holds the current status of the certificate. Will be displayed and managed in UI.</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute default="true" name="active" type="boolean">
            <annotation>
                <documentation>Whether this certificate can be used by the proxy.</documentation>
            </annotation>
        </attribute>
        <attribute name="id" type="ID" use="optional">
            <annotation>
                <documentation>ID for cert that is used by the OCSP request keys.</documentation>
            </annotation>
        </attribute>

    </complexType>
    <complexType name="DeviceType">
        <sequence>
            <element name="deviceType" type="string">
                <annotation>
                    <documentation>This is pointer to the device type configuration.</documentation>
                </annotation>
            </element>
            <element name="friendlyName" type="string" minOccurs="0">
                <annotation>
                    <documentation>Name that is displayed in UI.</documentation>
                </annotation>
            </element>
            <element name="id" type="string">
                <annotation>
                    <documentation>This is identifier that will be used to refer to this device in the APIs.</documentation>
                </annotation>
            </element>
            <element minOccurs="0" name="tokenId" type="string">
                <annotation>
                    <documentation>Id of the token (serial number)</documentation>
                </annotation>
            </element>
            <element minOccurs="0" name="slotId" type="string">
                <annotation>
                    <documentation>Id of the slot (label)</documentation>
                </annotation>
            </element>
            <element minOccurs="0" name="pinIndex" type="int" default="1">
                <annotation>
                    <documentation>Pin index (in case slot id does not identify the correct token)</documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="key" type="tns:KeyType"/>
            <element name="signMechanismName" type="string" minOccurs="0" default="CKM_RSA_PKCS">
                <annotation>
                    <documentation>Signing (PKCS#11) mechanism name.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    <complexType name="CertRequestType">
        <sequence>
            <element minOccurs="0" name="memberId" type="id:XRoadClientIdentifierType">
                <annotation>
                    <documentation>Identifies the member on whose behalf the certificate request was sent. Not present on authentication keys.</documentation>
                </annotation>
            </element>
            <element name="subjectName" type="string">
                <annotation>
                    <documentation>The DN component that went into the certification request. Encoded as string.</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="id" type="ID" use="optional">
            <annotation>
                <documentation>ID of this element, mostly used by UIs.</documentation>
            </annotation>
        </attribute>
    </complexType>
</schema>

=== nordic-institute/X-Road/src/proxy/core/src/test/keyconftest.xml
<tns:keyConf xmlns:tns="http://x-road.eu/xsd/xroad.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://x-road.eu/xsd/xroad.xsd ../main/resources/keyconf.xsd ">
    <device>
        <deviceType>softToken</deviceType>
        <id>1</id>
        <key usage="SIGNING">
            <friendlyName>Producer active signing key friendly name</friendlyName>
            <keyId>70726f6475636572</keyId>
            <!-- Extracted from ../sandbox/src/main/resources/producer.p12 -->
            <cert memberId="producer" active="true">MIIDiDCCAnCgAwIBAgIIPl9RxHk9tEQwDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                HhcNMTIwOTI4MTgxODIxWhcNMTQwOTI4MTgxODIxWjATMREwDwYDVQQDDAhwcm9k
                dWNlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL6kZcfiqsmviMOo
                PlZ70wiy8/W05Ks+OlbPE72LWFMjsxbV/LAnsR4NZhJSaWfKLTkmjeAz+ZPE57gB
                fKDeLZePvI5UgXx8ICv335u5xZdGPQQdKI0jymU518KVYzQEvStJarkul/tPBpJU
                AWLH8OWcHlWes107tb9pA0e8IAM3TzlPQTfqCYhEBBEuk3KelWB4OyN4vz2g/X8a
                wEfDrdpnD04M4V6dnFmqNJkzqH/NrG+8gs6KNpei0oyo6Oxzh34jD8dIxHGsyQlY
                cX+ojtAUSP8al87RJYo5R9lTZTo3VzzOZU8k7+9l87x09DjCBpsV+NrgFdMfN0yq
                8+fRHekCAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGGPGh0
                dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dlYi9z
                dGF0dXMvb2NzcDAdBgNVHQ4EFgQUOSov6/KI/czxIZu50J/za2u8vPMwDAYDVR0T
                AQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNVHQ8B
                Af8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBAAah21Rhpo+MwvkJZI+sUu3CgejK
                GvLWNT4LEZQqFNl2QuKsFRlmV9nIo9SZND0jclp2GFj4i9uD+kuMZ2++5bq0tWqo
                F5GsBeILwxuNxwapaB8ZUGoyn2OZu17LzZhevlBP40NjuOW19L0meFsh7gxgbWhz
                nR+lrzpZheprvEgRkaVoBcCLcMVh4DLGO935xQHUStbyrKaCl+UDu+vBzCwes8oO
                rIPNU/TOoRzws9/NiIHeJxVBN2Jf0C3C7H58O3gmbqcBclfoBo5N5nQaeAs8ASXA
                SxcscVUoREaKExjoSIC+KMXhSESWdc7Prswii7i1i/l/ITMpNLr29O/0FPY=
            </cert>
        </key>
        <key usage="SIGNING">
            <friendlyName>Consumer active signing key friendly name</friendlyName>
            <keyId>636f6e73756d6572</keyId>
            <!-- Extracted from ../sandbox/src/main/resources/consumer.p12 -->
            <cert memberId="consumer" active="true">MIIDiDCCAnCgAwIBAgIIW99Q5VUloqswDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                HhcNMTIwOTI4MTgxNzM5WhcNMTQwOTI4MTgxNzM5WjATMREwDwYDVQQDDAhjb25z
                dW1lcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAILY5AcoHHeoHIYq
                rrjaadQJwJlwMFN8mT/txE4/oKUWecvikwk1RNJNH0s+D9iUoCsCYqlU7PXbIXIe
                lkH08ehgsdi5OmNAiG0fxEIouPDDOg5L5c4wxOm1/vVf0H+yBrv1OWUfEnCwsiRm
                qRN1JU9LH1GkVulPdqCMbicqlbidTTfYcFwf4R7RfOFeHrrNJSBvRev+TUt+Jnwb
                O4vHFxhGDBXMLwiNZdedhE9NO3zUorWPEiVNapp/u0agMXAv3RmJsIGeVJerGFay
                7Eb9RbhTcHOePGl1IetV7J3A9L14OqauMShaFJQUnTXSqS8ldcge/JfgSiWTqE0T
                jVc0pYMCAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGGPGh0
                dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dlYi9z
                dGF0dXMvb2NzcDAdBgNVHQ4EFgQU25SlUgQRwFCiraz2euhPUBqpvj0wDAYDVR0T
                AQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNVHQ8B
                Af8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBAFFWRyInsq/jKrW20BKzRr2KAAnE
                2nDVmZLFfcv7ZwrLOOJYkHxdPEfkcXcwJy4B1KJdvm0+1FlgfoKgDiUjTRbXraXm
                yUwAL5s5yMr9wFwu9N9JL6IwchMNT6S5zwA+iioLMQbHAMfwXXSS/Vp7aUxmejK4
                XbNtehsukalD7S3ILAK7dtamPr0YvRqUBbj4k9zD60gVU13jmACr/JuSXI4Jxyoi
                FdUNDdtQbiiGOsrOuLmc/WbzXNo7iN/zhwEMJNJThtyGYthhiYeZKT+0B5Yy/sAR
                kinWqLpUwddf+plfH+4HP2akrt8uoHSZXKKOmN8IlXgN89LPVBC+oSltnhY=</cert>
        </key>
        <key usage="SIGNING">
            <friendlyName>For testing faulty cases</friendlyName>
            <!-- Extracted from ../sandbox/src/main/resources/consumer.p12 -->
            <cert memberId="consumer" active="true">MIIDiDCCAnCgAwIBAgIIW99Q5VUloqswDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                HhcNMTIwOTI4MTgxNzM5WhcNMTQwOTI4MTgxNzM5WjATMREwDwYDVQQDDAhjb25z
                dW1lcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAILY5AcoHHeoHIYq
                rrjaadQJwJlwMFN8mT/txE4/oKUWecvikwk1RNJNH0s+D9iUoCsCYqlU7PXbIXIe
                lkH08ehgsdi5OmNAiG0fxEIouPDDOg5L5c4wxOm1/vVf0H+yBrv1OWUfEnCwsiRm
                qRN1JU9LH1GkVulPdqCMbicqlbidTTfYcFwf4R7RfOFeHrrNJSBvRev+TUt+Jnwb
                O4vHFxhGDBXMLwiNZdedhE9NO3zUorWPEiVNapp/u0agMXAv3RmJsIGeVJerGFay
                7Eb9RbhTcHOePGl1IetV7J3A9L14OqauMShaFJQUnTXSqS8ldcge/JfgSiWTqE0T
                jVc0pYMCAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGGPGh0
                dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dlYi9z
                dGF0dXMvb2NzcDAdBgNVHQ4EFgQU25SlUgQRwFCiraz2euhPUBqpvj0wDAYDVR0T
                AQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNVHQ8B
                Af8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBAFFWRyInsq/jKrW20BKzRr2KAAnE
                2nDVmZLFfcv7ZwrLOOJYkHxdPEfkcXcwJy4B1KJdvm0+1FlgfoKgDiUjTRbXraXm
                yUwAL5s5yMr9wFwu9N9JL6IwchMNT6S5zwA+iioLMQbHAMfwXXSS/Vp7aUxmejK4
                XbNtehsukalD7S3ILAK7dtamPr0YvRqUBbj4k9zD60gVU13jmACr/JuSXI4Jxyoi
                FdUNDdtQbiiGOsrOuLmc/WbzXNo7iN/zhwEMJNJThtyGYthhiYeZKT+0B5Yy/sAR
                kinWqLpUwddf+plfH+4HP2akrt8uoHSZXKKOmN8IlXgN89LPVBC+oSltnhY=</cert>
        </key>
        <key usage="AUTHENTICATION">
            <friendlyName>Seda me autentimiseks kasutame</friendlyName>
            <keyId>70726f6475636572</keyId>
            <!-- Extracted from ../sandbox/src/main/resources/producer.p12 -->
            <cert memberId="producer" active="true">MIIDiDCCAnCgAwIBAgIIPl9RxHk9tEQwDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                HhcNMTIwOTI4MTgxODIxWhcNMTQwOTI4MTgxODIxWjATMREwDwYDVQQDDAhwcm9k
                dWNlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL6kZcfiqsmviMOo
                PlZ70wiy8/W05Ks+OlbPE72LWFMjsxbV/LAnsR4NZhJSaWfKLTkmjeAz+ZPE57gB
                fKDeLZePvI5UgXx8ICv335u5xZdGPQQdKI0jymU518KVYzQEvStJarkul/tPBpJU
                AWLH8OWcHlWes107tb9pA0e8IAM3TzlPQTfqCYhEBBEuk3KelWB4OyN4vz2g/X8a
                wEfDrdpnD04M4V6dnFmqNJkzqH/NrG+8gs6KNpei0oyo6Oxzh34jD8dIxHGsyQlY
                cX+ojtAUSP8al87RJYo5R9lTZTo3VzzOZU8k7+9l87x09DjCBpsV+NrgFdMfN0yq
                8+fRHekCAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGGPGh0
                dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dlYi9z
                dGF0dXMvb2NzcDAdBgNVHQ4EFgQUOSov6/KI/czxIZu50J/za2u8vPMwDAYDVR0T
                AQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNVHQ8B
                Af8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBAAah21Rhpo+MwvkJZI+sUu3CgejK
                GvLWNT4LEZQqFNl2QuKsFRlmV9nIo9SZND0jclp2GFj4i9uD+kuMZ2++5bq0tWqo
                F5GsBeILwxuNxwapaB8ZUGoyn2OZu17LzZhevlBP40NjuOW19L0meFsh7gxgbWhz
                nR+lrzpZheprvEgRkaVoBcCLcMVh4DLGO935xQHUStbyrKaCl+UDu+vBzCwes8oO
                rIPNU/TOoRzws9/NiIHeJxVBN2Jf0C3C7H58O3gmbqcBclfoBo5N5nQaeAs8ASXA
                SxcscVUoREaKExjoSIC+KMXhSESWdc7Prswii7i1i/l/ITMpNLr29O/0FPY=
            </cert>
        </key>
    </device>
</tns:keyConf>
